# Generated by Django 5.1.5 on 2025-03-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_appointment_address_appointment_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('General Medicine', 'General Medicine'), ('Cardiology', 'Cardiology'), ('Pediatrics', 'Pediatrics'), ('Orthopedics', 'Orthopedics'), ('Gastrology', 'Gastrology'), ('Physiotherapist', 'Physiotherapist'), ('Neurology', 'Neurology'), ('Gynaecologist', 'Gynaecologist')], default=123, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='fee',
            field=models.IntegerField(default=400),
        ),
    ]
