# Generated by Django 5.1.5 on 2025-03-05 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentschedule',
            name='doctor_notes',
        ),
    ]
